#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class Credito
	{
		private int _idCredito;
		public virtual int IdCredito
		{
			get
			{
				return this._idCredito;
			}
			set
			{
				this._idCredito = value;
			}
		}
		
		private string _nroCredito;
		public virtual string NroCredito
		{
			get
			{
				return this._nroCredito;
			}
			set
			{
				this._nroCredito = value;
			}
		}
		
		private int? _idCliente;
		public virtual int? IdCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				this._idCliente = value;
			}
		}
		
		private DateTime? _fechaLiquidacion;
		public virtual DateTime? FechaLiquidacion
		{
			get
			{
				return this._fechaLiquidacion;
			}
			set
			{
				this._fechaLiquidacion = value;
			}
		}
		
		private int? _idGarante;
		public virtual int? IdGarante
		{
			get
			{
				return this._idGarante;
			}
			set
			{
				this._idGarante = value;
			}
		}
		
		private int? _idUsuario;
		public virtual int? IdUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				this._idUsuario = value;
			}
		}
		
		private string _estadoRegistro;
		public virtual string EstadoRegistro
		{
			get
			{
				return this._estadoRegistro;
			}
			set
			{
				this._estadoRegistro = value;
			}
		}
		
		private Cliente _cliente;
		public virtual Cliente Cliente
		{
			get
			{
				return this._cliente;
			}
			set
			{
				this._cliente = value;
			}
		}
		
		private Garante _garante;
		public virtual Garante Garante
		{
			get
			{
				return this._garante;
			}
			set
			{
				this._garante = value;
			}
		}
		
		private Usuario _usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				this._usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
